-- AlterTable: Users - Rechnungsadresse hinzufügen
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "company" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "street" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "zipCode" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "country" TEXT NOT NULL DEFAULT 'DE';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "vatId" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "website" TEXT;

